FROM tomcat:9
EXPOSE 8080

RUN apt-get update -y
RUN apt-get install gettext-base apache2-utils -y

ARG VERSION=1.9.1
ARG BUILD='v1.9.1'
ARG RELEASE_TYPE=release

ENV PWM_VERSION         ${VERSION}
ENV PWM_APPLICATIONPATH /usr/local/pwm
ENV CONFIG_XML_BASE64   'MIIDeTCCAmGgAwIBAgIQQpw4iVv455hKiMXwVOZELjANBgkqhkiG9w0BAQsFADBCMRMwEQYKCZImiZPyLGQBGRYDdmh0MRowGAYKCZImiZPyLGQBGRYKdGVzdGRvbWFpbjEPMA0GA1UEAxMGVkhULUNBMCAXDTIwMTAyOTA5MDM0NloYDzIxMTkxMDI5MDkxMzQ2WjBCMRMwEQYKCZImiZPyLGQBGRYDdmh0MRowGAYKCZImiZPyLGQBGRYKdGVzdGRvbWFpbjEPMA0GA1UEAxMGVkhULUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAre5mozrRmymZvrJ3ECmeXhPM+tZyOfwGqWHWqs1JFkm4FQ7dFPIHkKbHTAII033TTwdCpLNQYUc2vmuo92YGD7ddmnfMJaWzMhyAIPeZ1QvoiSfyEBa5uw7h8Zowcz+8TLrYA3byJnqGBSn4qB77FELCVuhUGZtqxYhYEK7EGPGO14B1cIWt+QYYdp6W/FcfOVXFt4kabZ2mzy17qWA8zrni1yQJ6dp36m8/bSzU6/dCF6QHM8H2jBiM5g8T/OzraJBtB8wM1N4KEiWrnen0uxpZLlV3lu6Gwk3Jz/k2nhRI7j2UeaJ70TxrB1s/H+GxySr4t8fCo+xssEXyyCtxHQIDAQABo2kwZzATBgkrBgEEAYI3FAIEBh4EAEMAQTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUQXw8PfpkeXGaf0T5yEGxspKFx+EwEAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggEBAAVWqM6J1JJXPvxQh7M2j0XeXrOb6Neor+J9bvwIO5frwa5MipG6fcvw1TexRwlltfdLe+VxmO22wUGjUaT6shh1haXW35XGVorq1kkTgaE0sP0nMTQUwT0hDP2UwbJ8yW7E6IavKZKsiy2pJ2i8B511cxql0AUp4yLD2mHvcXw0AyJCUudS35vWSXLeVqeQIsN9HT6A8kRn3gnRbvKtdyCiitkrD1VOzbxYCprM+Pk/JJhkFkeZvHw6sDSFCjXAEkV2S/0XywUJ5NjBcRqoD4Bc2DgSLEzT6J6vjP75V/Kzarm9h86dgDCoT7TzHKQFoQ+6wWhauQqYzGanSySV5l8='

# COPY pwm-1.9.1.war "${CATALINA_HOME}/webapps/ROOT.war"
RUN curl -f https://www.pwm-project.org/artifacts/pwm/${RELEASE_TYPE}/${BUILD}/pwm-${VERSION}.war -o "${CATALINA_HOME}/webapps/ROOT.war"
RUN mkdir -p "${PWM_APPLICATIONPATH}/logs"
RUN echo 'Initializing PWM...' > "${PWM_APPLICATIONPATH}/logs/PWM.log"
COPY startup.sh .
RUN ["chmod", "+x", "./startup.sh"]
CMD ["./startup.sh"]